config/routes.rb
Rails.application.routes.draw do

  scope module: :web do
    get 'welcome/index'

    namespace :moderation do
      resources :articles, only: [:index, :show, :edit] do
        patch :moderate, on: :member
      end
    end

    resources :articles do
      scope module: :articles do
        resources :comments, only: [:create, :destroy] do
          scope module: :comments do
            resources :likes, only: [:create]
          end
        end
      end
      patch :send_to_moderation, on: :member
    end
  end

  root 'web/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :links, inverse_of: :article, dependent: :destroy
  belongs_to :category, optional: true

  validates :title, presence: true,
                    length: { minimum: 5 }

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  state_machine :state, initial: :draft do
    state :draft
    state :on_moderation
    state :published

    event :send_to_moderation do
      transition :draft => :on_moderation
    end

    event :moderate do
      transition :on_moderation => :published
    end
  end
end

app/models/article/category.rb
class Article::Category < ApplicationRecord
  has_many :articles, dependent: :nullify
end

app/models/article/comment.rb
class Article::Comment < ApplicationRecord
  belongs_to :article
  has_many   :likes

  validates :commentor, presence: true
  validates :body, presence: true
end

app/models/article/comment/like.rb
class Article::Comment::Like < ApplicationRecord
  belongs_to :comment

  scope :recent, -> { where('"created_at" < ?', 1.hour.ago) }
end

app/models/article/link.rb
class Article::Link < ApplicationRecord
  belongs_to :article, inverse_of: :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles/application_controller.rb
class Articles::ApplicationController < ApplicationController
  http_basic_authenticate_with name: "viraj", password: "password", except: [:index, :show]

  protect_from_forgery with: :exception
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < Articles::ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:article_comment).permit(:commentor, :body)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "viraj", password: "password", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "viraj", password: "password", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commentor, :body)
  end
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
end

app/controllers/web/articles/application_controller.rb
class Web::Articles::ApplicationController < Web::ApplicationController
  def resource_article
    requested_article
  end

  def requested_article
    Article.find(params[:article_id])
  end
end

app/controllers/web/articles/comments/application_controller.rb
class Web::Articles::Comments::ApplicationController < Web::Articles::ApplicationController
  def resource_comment
    requested_comment
  end

  def requested_comment
    resource_article.comments.find(params[:comment_id])
  end
end

app/controllers/web/articles/comments/likes_controller.rb
class Web::Articles::Comments::LikesController < Web::Articles::Comments::ApplicationController
  def create
    if resource_comment.likes.recent.count <= 5
      resource_comment.likes.create
      redirect_to article_path(resource_article)
    else
      render :forbidden
    end
  end
end

app/controllers/web/articles/comments_controller.rb
class Web::Articles::CommentsController < Web::Articles::ApplicationController
  def create
    @comment = resource_article.comments.create(comment_params)
    redirect_to article_path(resource_article)
  end

  def destroy
    @comment = resource_article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(resource_article)
  end

  private

  def comment_params
    params.require(:article_comment).permit(:commentor, :body)
  end
end

app/controllers/web/articles_controller.rb
class Web::ArticlesController < Web::ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  def send_to_moderation
    @article = Article.find(params[:id])
    @article.send_to_moderation!

    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :category_id, links_attributes: [:id, :_destroy, :url])
  end
end

app/controllers/web/moderation/application_controller.rb
class Web::Moderation::ApplicationController < Web::ApplicationController
end

app/controllers/web/moderation/articles_controller.rb
class Web::Moderation::ArticlesController < Web::ApplicationController
  def index
    default_ransack_params = { state_eq: 'on_moderation' }
    @q = Article.ransack(params[:q] || default_ransack_params)

    @articles = @q.result(distinct: true)
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article::ModerationType.find(params[:id])
  end

  def moderate
    @article = Article::ModerationType.find(params[:id])
    if @article.update(params[:article])
      @article.moderate!
      redirect_to @article
    else
      render 'edit'
    end
  end

  private

  def article_params
    params.require(:article).permit(:category_id)
  end
end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/web/articles/_form.html.erb
<%= simple_form_for @article do |f| %>

  <p>
    <%= f.input :title %>
  </p>

  <p>
    <%= f.input :text %>
  </p>

  <h3>Links</h3>

  <div id="links">
    <%= f.simple_fields_for :links do |link| %>
      <%= render 'link_fields', f: link %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add link', f, :links %>
    </div>
  </div>

  <p>
    <%= f.button :submit %>
  </p>

<% end %>

app/views/web/articles/_link.html.erb
<%= link_to link.url, link.url %><br>

app/views/web/articles/_link_fields.html.erb
<div class="nested-fields">
  <%= f.input :url %>
  <%= link_to_remove_association "remove link", f %>
</div>

app/views/web/articles/comments/_comment.html.erb
<p>
  <strong>Commentor:</strong>
  <%= comment.commentor %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
<%= link_to 'Delete comment', article_comment_path(comment.article, comment),
method: :delete,
data: { confirm: 'Are you sure?' } %>
</p>
.........................................

app/views/web/articles/comments/_form.html.erb
<%= simple_form_for @article.comments.build, url: article_comments_path(@article) do |f| %>
  <p>
    <%= f.input :commentor %>
  </p>
  <p>
    <%= f.input :body %>
  </p>
  <p>
    <%= f.button :submit %>
  </p>
<% end %>

app/views/web/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>


<%= link_to 'Send to moderation', send_to_moderation_article_path(@article), method: :patch if @article.draft? %>
<%= link_to 'Back', articles_path %>

app/views/web/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/web/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= render partial: 'web/articles/link', collection: @article.links %>

<h2>Comments</h2>
<%= render partial: 'web/articles/comments/comment', collection: @article.comments %>

<h2>Add a comment:</h2>
<%= render 'web/articles/comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/web/moderation/articles/_form.html.erb
<%= simple_form_for @article, url: moderate_moderation_article_path(@article) do |f| %>

  <p>
    <%= f.association :category %>
  </p>

  <p>
    <%= f.button :submit %>
  </p>

<% end %>

app/views/web/moderation/articles/edit.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/web/moderation/articles/index.html.erb
<h1>Articles: </h1>

<%= search_form_for @q, url: moderation_articles_path do |f| %>
    <%= f.label :title_cont %>
    <%= f.search_field :title_cont %>

    <%= f.label :state_eq %>
    <%= f.select :state_eq, ['', 'draft', 'on_moderation', 'published'] %>

    <%= f.submit %>
  <% end %>

<table>
  <tr>
    <th><%= sort_link(@q, :title) %></th>
    <th>Text</th>
    <th><%= sort_link(@q, :category) %></th>
    <th><%= sort_link(@q, :state) %></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= article.category&.name %></td>
      <td><%= article.human_state_name %></td>
      <td><%= link_to 'Show', moderation_article_path(article) %></td>
      <td><%= link_to 'Edit', edit_moderation_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
      method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/web/moderation/articles/moderate.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/web/moderation/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render partial: 'web/articles/comments/comment', collection: @article.comments %>

<h2>Add a comment:</h2>
<%= render 'web/articles/comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>